app/Http/Controllers/TicketController.php
composer.json
composer.lock
resources/lang/en/errors.php

This PR fixes issue #4 by clearing cache on a try/catch with pulling the ticket number and display a invalid ID error.

Fix Catch issue with TicketController and upgrades sonarsoftware/customer_portal_framework version

---

README.md

A small visual meta PR. Thanks!

[meta] Added screenshot on README.md

---

public/assets/js/pages/settings/settings.js
resources/views/pages/config/show.blade.php

Adjusting JS to pull from new endpoint for subdivisions on the settings page.

JS state issue adjustments

---

app/Http/Controllers/SubdivisionController.php
public/assets/js/pages/settings/settings.js
resources/views/pages/config/show.blade.php
routes/web.php

Prior to change when selecting a different country the state dropdown would disappear. Worked with @alectrocute to resolve this issue by creating a new endpoint and adjusting the JS.

Fixed State issue with disappearing on settings page

---

resources/lang/en/errors.php
resources/lang/fr/errors.php
resources/views/errors/500.blade.php

Setup error page to assist with failures on the settings page.

Setup a 500 error page for failures

---

resources/views/pages/profile/show.blade.php

Removed role from customer portal

---

app/Http/Controllers/BillingController.php
public/assets/css/theme.css
resources/views/pages/billing/index.blade.php
routes/web.php

Setup pagination on main page. Also setup CSS on this as well. Below is the screen shot on recent transactions. Current limit is 5 per page.
Invoice:
@SonarSoftware we can go through a live demo on this design if you want to.

Setup pagination for transactions and invoices

---

.gitignore
resources/views/vendor/pagination/bootstrap-4.blade.php
resources/views/vendor/pagination/default.blade.php
resources/views/vendor/pagination/semantic-ui.blade.php
resources/views/vendor/pagination/simple-bootstrap-4.blade.php
resources/views/vendor/pagination/simple-default.blade.php

View files where missing for the pagination. Changed .gitignore to ignore /vendor but allow vendor on sub.

Change gitignore from vendor to /vendor due to view files

---

package.json

Axios is not in use and was saved within package.json

Removed axios from dev dependencies

---

resources/views/pages/config/show.blade.php

Added additional currency to gocardless

---

composer.lock

Updated from 1.0.13 to 1.0.14 with the customer_portal_framework

Updated Customer Portal Framework

---

public/assets/js/pages/billing/payment/page.js

Issue with button not disappearing correctly when hitting in live environment. Adjusted and verified in production.

Fixed disable button

---

resources/views/pages/billing/index.blade.php

Added 4 stars to the bank account within the customer portal to be similar as the sonar instance per customer request.

Added 4 stars on bank account

---

public/assets/js/pages/billing/payment/page.js

Fixed existing payment button.
Verify with @sonar-matt on jquery side and in dev env

Fixed Existing Payment Button

---

README.md
install.sh

Add check to install.sh for running as root and http binding problems; updated README to reflect differences between SonarV1 and SonarV2 role definitions.

Minor edits

---

install.sh

Fixed install script breaking when reviewing current listening ports. Tested on prod server and local dev.

Fixed install script

---

app/Http/Controllers/BillingController.php
app/Http/Controllers/ProfileController.php
app/Http/Requests/CreateBankAccountRequest.php
composer.json
composer.lock
resources/views/pages/billing/add_bank.blade.php

Fixed adding bank into v2 from the portal

Updated framework and fixed bank account adding for v2

---

public/assets/css/theme-root.css

Fixes issue https://github.com/SonarSoftwareInc/customer_portal/issues/73

Added alerts-success styles to theme root

---

composer.json
composer.lock

Updating customer framework to remove the role of the updateContact

Fixed null on role

---

public/assets/css/theme.css

Dropdowns now show.
This doesn't effect scrolling of the table component, tested with multiple credit cards and contracts

[AB#2690] This blocks the dropdowns from showing on iphone

---

app/Http/Controllers/BillingController.php
deploy/conf/nginx/sonar-customerportal.template
resources/views/pages/billing/index.blade.php
resources/views/pages/data_usage/index.blade.php

Requires a UBB, overage service with CREDIT type.

[AB#3330] Adding ability to purchase a top off directly from customer portal

---

resources/views/pages/root/index.blade.php

Forms where nested, caused submission error. Removed nesting and login works again.

Update index.blade.php nested forms

---

resources/lang/en/billing.php
resources/lang/fr/billing.php
resources/views/pages/billing/add_bank.blade.php
resources/views/pages/billing/index.blade.php

This is the first time I did anything in portal. Be very critical.

[AB#3747] Add autopay checkbox to bank account form

---

composer.json
composer.lock

something goes bump in the night

Ab7922: Defrenchifying subdivisions

---

app/Http/Controllers/AppConfigController.php
resources/views/pages/config/show.blade.php

AB#11407 Added XCD / East Caribbean dollars to the Paypal and Gocardless

---

resources/views/pages/billing/index.blade.php

fixed the text bug by adding a quotation mark

Customer portal - Disable Autopay button displays extra text

---

app/Http/Controllers/BillingController.php

company_id can be null in v1 sonar.  This adds the check to avoid an error on those portals.

AB#32905 Support for v1 in client portal fcc fixes

---

composer.json
composer.lock

References new framework that has fix for expiry year issue.

AB#33403 Fix expiry year

---

okteto.yml

Couldn't okteto up into the instance

AB#35627 - Updating okteto config

---

public/assets/js/pages/tickets/create.js
public/assets/js/pages/tickets/show.js
resources/views/pages/tickets/create.blade.php
resources/views/pages/tickets/show.blade.php

Disabled submit button on form submit to prevent users from clicking again.

AB#30369 - Clicking Submit multiple times on a single ticket, creates duplicate tickets.

---

lang/es/headers.php

Spanish translations got merged in, this is just to add in a new feature that got merged in while it was worked on.

AB#35771 - Adding account translation

---

app/Http/Kernel.php
app/Http/Middleware/AddSecurityHeaders.php

Ensure security headers are added to responses

AB#32579 - Customer Portal - PCI Audit Reports: CWE-693 HTTP Security Header Not Detected

---

resources/views/layouts/partials/nav.blade.php

Menu selector was broken when bootstrap was upgraded to 5.3

AB#35509 - Fixing mobile menu selector
