SonarSoftwareInc/customer_portal

README.md, public/assets/css/theme-root.css, public/assets/css/theme.css
The update of jQuery re-enabled some client-side validation classes, so this PR assigns the relevant CSS to make errors distinctive for the user.
Also removed the direct image link for the `README.md`.
=> Added styling for form validation classes

README.md
Within README the volume name was `customerportal_storage` the correct name is `customer_portal_storage`
=> Fixed volume name on troubleshooting steps

install.sh
Reference Issue #21 
Install script was showing `Enter Your Instance URL (e.g. https://portal.example.com):` when it needs to show `Enter Your Instance URL (e.g. https://example.sonar.software):`
This was causing confusion when installing the customer portal.
=> Fixed install script showing url.

resources/views/pages/billing/index.blade.php
Missed removing translation on the last PR. This removes that translation on the dashboard screen.
=> Removed translation on the noGoCardless

README.md
Currently the permissions aren't showing clearly within the readme file along with the permission change from v1 to v2 customer portal.
=> Adjusted the readme to show the permission required clearly

resources/views/pages/billing/index.blade.php
000 and 123 was set for CC and Bank Account. This was only a place holder when the portal was being built.
=> Removed placeholder config for CC and Bank Account

app/Http/Controllers/BillingController.php, app/Http/Controllers/PayPalController.php
When the integration with paypal was set if you click on make a payment it wouldn't redirect. Corrected this issue and tested within sandbox and live environment.
=> Fixed issue with paypal not redirecting when clicking make payment

app/Http/Controllers/AppConfigController.php, resources/views/pages/config/show.blade.php
When configuring paypal and selecting a currency it would save the array index instead of the value. Adjusted to match what paypal requires. Tested locally within the paypal.
=> Fixed issue with paypal currency

resources/views/pages/billing/index.blade.php
This was initially fixed in PR #32 but reappeared in the latest release.
=> Fixed placeholder test for CC and bank accounts

resources/views/pages/billing/index.blade.php
Prior the payment button would only display if an amount was due. Setup to display the payment button at all times.
=> Added payment button

app/Http/Controllers/ProfileController.php, resources/views/pages/profile/show.blade.php
Currently only accepts US numbers within the customer portal. Setup if not selected on US then remove data-mask to allow other country formats.
Verified worked with UK and US phone numbers
=> Allow more than 9 digit phone numbers

app/Http/Controllers/BillingController.php
Setup additional logging to attempt to track down the random CC payment reported failure while on success.
=> Setting up additional logging

app/Http/Controllers/BillingController.php, public/assets/js/pages/billing/payment/page.js, resources/views/pages/billing/make_payment.blade.php
This PR is to fix an issue with customers hitting the pay button multiple times when the first call hasn't completed yet.
- Disable the button on submit if page validation passes. If any element contains "error" (example city-error) then keep the button enabled.
- Removed detailed logging
=> Disable button on submit

public/assets/js/pages/billing/payment/page.js
The button would sometimes become disabled after clicking submit with no errors on the page. Now we are running a very min validation to make sure values are set on the form before disabling the button.
=> Button Bug Fix - Disappearing on errors

Dockerfile, resources/views/pages/config/show.blade.php
Corrected spelling issue with `Separator` in config page.
=> Fixed misspelling in config page

Dockerfile, deploy/90_init_fpm.sh, deploy/conf/nginx/sonar-customerportal.template, deploy/services/php-fpm.sh
The version of swiftmailer used in Laravel 5.5 does not work with PHP 7.4 due to its dependency on egulias/EmailValidator: https://github.com/egulias/EmailValidator/issues/212
Bump PHP back for now.
=> Revert PHP to 7.3

resources/views/pages/billing/make_payment.blade.php
Customer portal payments are not applying, the only issue I could see was that the closing form/div tag where out of order, and the browser showed that as an error. Re-ordered the tags and it seems to work now (for submit payment)
=> Unclosed Tag

Dockerfile
Error in log -> 
sonar-customerportal | Feb 10 17:10:02 f1cb88058c97 cron[76]: (*system*laravel-cron) INSECURE MODE (group/other writable) (/etc/cron.d/laravel-cron)
sonar-customerportal | Feb 10 17:10:02 f1cb88058c97 cron[76]: (*system*nginx-reload-certs) INSECURE MODE (group/other writable) (/etc/cron.d/nginx-reload-certs)
Fixed by applying permissions 600/644 to /etc/cron.d (cron jobs aren't running)
=> Updated cron job permissions

resources/views/pages/billing/make_payment.blade.php
Input tag does not have a steps attribute. step=any allows decimal places. If undefined default is 1
=> Changed steps to step

deploy/conf/nginx/sonar-customerportal.template
script-scr self disallows inlining, added the hashes for the three scripts in payment that are inline scripts so they CSP doesn't shut them down.
=> Added hashes for inline JS scripts for CSP

install.sh
newest version of containerd causes install to fail; locking at 1.4.4-1
=> Lock containerd.io at version 1.4.4-1

Dockerfile
Update storage volume in Dockerfile otherwise okteto will not deploy the containers.
The image below should be tagged and pushed as `sonarsoftware/customerportal:latest`, as the `okteto.Dockerfile` specifies the `latest` tag (I cannot push to the repository).
https://hub.docker.com/layers/sonarsoftware/customerportal/83efbaf1240a552ffa030ba99ce8a3fddd833785/images/sha256-cb5911ce150ad12a112c80e771d47a2864bb37a6a8045e0d3f276640b089468c?context=explore
Discussion: https://sonarsoftware.slack.com/archives/G01G864R26A/p1624400116043100
=> Change volume definition in Dockerfile

app/Http/Controllers/DataUsageController.php, resources/views/pages/billing/index.blade.php
https://dev.azure.com/sonarsoftware/Sonar/_workitems/edit/3212
In sonar (v2), whenever an account transitions from some status to 'Active', a HistoricalDataUsage is created for it. This didn't always happen, though - so there are accounts with no HistoricalDataUsage, which will break the Data Usage and Billing pages of the Customer Portal. 
Here, we add some conditions to provide default values if the history doesn't exist. 
There is another PR in sonar to create DataUsageHistories for all active accounts, which is this: https://github.com/SonarSoftwareInc/sonar/pull/3305. Which should prevent these conditions from ever being needed. 
Instead of
=> AB#3212 Don't break the page if there is no historical data usage.

resources/views/pages/config/show.blade.php
Related to the V1 stripe Stripe PR. 
Removes this text in `customer-portal.com/settings`
=> Remove Stripe API token message about v2/v1

okteto-stack.yml, public/assets/css/theme.css, public/assets/svg/breadcrumb-mask.svg, public/assets/svg/carousel-next.svg, public/assets/svg/carousel-prev.svg, public/assets/svg/cb-checked.svg, public/assets/svg/cb-indeterminate.svg, public/assets/svg/radio-checked.svg, public/assets/svg/select.svg, public/assets/svg/sort.svg, public/assets/svg/toggler-dark.svg, public/assets/svg/toggler-light.svg
Allowing the `data:` schema for sources in the CSP is inherently unsafe. CSP doesn't have an easy way to allow some uses of `data:`.
From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src):
> This is insecure; an attacker can also inject arbitrary data: URIs. Use this sparingly and definitely not for scripts.
Inlining svgs in css avoids the multiple HTTP connections needed to fetch the multiple files, but http/2 makes this much less beneficial because the same connection is reused for fetching multiple assets.
This PR moves all inlined CSS background-image and mask SVG into SVG files and references those files in the CSS. This avoids the need to modify the CSP.
=> AB#5540 CSP is preventing loading of legitimate resources

resources/views/layouts/partials/js.blade.php, resources/views/pages/billing/index.blade.php
This PR fixes a couple of CSP violations on the billing index page caused by some inlined JS in onclick attributes of buttons. I extracted the onclick to a function and added event listeners for the few buttons that needed it.
Before, when clicking the enable/disable autopay button on a credit card, the request is in flight but the button content has not updated:
After, when clicking the enable/disable autopay button on a credit card, the request is in flight and the button content has updated:
=> AB#4334 Fix CSP violations

.circleci/config.yml, Dockerfile, README.md, install.sh
* Tested script and image with no issues.
* Docker image will be upgraded to jammy:1.0.0 (Ubuntu 22.04 LTS)
* Tested host node as Ubuntu 22.04 LTS as well. Adjusted install script accordingly.
=> Upgrade to Ubuntu 22.04 LTS

composer.json, composer.lock
Laravel 10 requires monolog 3.
Monolog 3 requires psr/log 2|3.
paypal/rest-api-sdk-php 1.14 requires psr/log 1.
We originally aliased psr/log 3 to 1 to satisfy paypal/rest-api-sdk-php, but psr/log 3 adds an explicit `void` return type in `LoggerAbstract` that causes a fatal error when extended. In psr/log 2 there is no specified return type on the abstract, and so paypal/rest-api-sdk-php 1.14 remains compatible.
=> AB#25101 customer portal paypal integration throws error

app/Http/Controllers/ProfileController.php, app/User.php, lang/en/errors.php, lang/fr/errors.php
Update: After rebasing, the most recent tiny commit was needed to clean up and needs a review before merging.
When saving phone numbers in the customer portal:
- Inputs will be kept after failures
- I've added the messaging below. If you have any suggestions for improving the text, please let me know.
Error Text: A phone number cannot be saved. Please remove it and try again.
This happens when there is phone number types mismatch between the customer portal and Sonar side. The customer portal will send Home, Mobile, Work, and Fax when they're set along with any other phone number types that are set Sonar side. However, the contact and phone numbers are loaded from the API and cached for 10 minutes, so this can cause some unexpected behavior when changing the phone number types on the …
=> AB#5796 customer portal cant add or update phone number from the portal

app/Http/Controllers/AuthenticationController.php, app/Http/Controllers/ProfileController.php, app/PasswordPolicy.php, composer.json, composer.lock, lang/en/errors.php, resources/views/pages/config/show.blade.php
Added server side password complexity checks to the customer portal. These checks will behave like the Minimum Password Strength setting sonar side. Updated settings page password complexity options to match the sonar options. Since the customer portal password complexity options that save to SQLite were accidentally created as 1-5 instead of 0-4 like zxcvbn outputs, the PasswordPolicy class is shifting them down to avoid a migration.
=> AB#10097 customer portal  password complexity is not being enforced

deploy/conf/nginx/sonar-customerportal.template, deploy/dev/sonar-customerportal-dev.template
This PR adds the `client_max_body_size` setting into the nginx site configuration and sets it to 8M, matching the fpm/php.ini `post_max_size` which is 8M by default.
=> AB#34508 nginx: Increase client max body size

UPGRADE.md, docker-compose.yml
Unfortunately when we added the FCC labels feature to client portal, we didnt make the upload directory a docker volume, so when the container resets, the FCC label zip needs to be uploaded again.
This makes the label directory persistent across restarts.
=> Fix FCC label disk volume

app/Http/Controllers/BillingController.php, public/assets/js/pages/billing/payment/page.js, public/assets/js/pages/billing/payment/page_stripe.js
It was possible to get this error to show up by changing the country code only after having an error caused by some other validation.  This was not then updating the "state" code which caused us to have a mismatch between the country code / state code that was not valid being passed to Sonar.  
When the country code is changed and the state select repopulated the first entry is considered selected and the value for that set.  
While not related to the issues it was also discovered that they expiration year was not being converted to an int explicitly as the month was so this has been adjusted as well.
=> AB#36289 - Customer Portal > Error Adding Credit Cards to Customer Portal

app/Http/Controllers/BillingController.php, lang/en/billing.php, resources/views/pages/billing/index.blade.php
Updated the Billing Controller to return multiple svgs (per data service on the account). In addition, I noticed the original `file_get_contents` was a touch slow to load the page. Instead I am returning the path and letting the template render the img from the assets path. I did notice a similar patter elsewhere - e.g: `<img class="logo-form" src="/assets/img/logo.png">` so I am assuming this is safe to do.
=> AB#37206 - Show multiple labels for FCC Broadband Facts.

Dockerfile
Updates the Docker image build to include the latest available ca-certificates package.
=> AB#38311 [HOTFIX] Fix expired security certificates

public/assets/js/pages/billing/payment/page.js, resources/views/pages/billing/add_bank.blade.php, resources/views/pages/billing/add_card.blade.php, resources/views/pages/billing/make_payment.blade.php
This PR takes care of two small Portal UI issues.
[Bug 36078](https://dev.azure.com/sonarsoftware/Sonar/_workitems/edit/36078): Customer Portal > Make a Payment - Country and State/Province revert to U.S.
This was a simple addition of blade's old() template function to retrieve the session data on validation redirects.
[Bug 36278](https://dev.azure.com/sonarsoftware/Sonar/_workitems/edit/36278): Customer Portal > Clicking submit multiple times adds duplicate bank account payment methods
Required a bit of JS to disable the button on submit.
=> AB#36078 - Submission Issues
